server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: app
    password: app
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  jta:
    enabled: true

management:
  endpoints.web.exposure.include: health,info,metrics,loggers
  endpoint.health:
    probes.enabled: true
    show-details: always

narayana:
  objectStoreDir: /opt/app/objectstore
  recovery:
    period: 120
    backoffPeriod: 30

broker:
  url: tcp://broker:61616
  user: admin
  pass: admin

cxf:
  path: /services
