spring:
  datasource:
    hikari:
      maximum-pool-size: 5
  sql:
    init:
      mode: always
# （local固有の差分だけを書く。brokerやDBの重複は原則削除）
management:
  endpoints.web.exposure.include: health,info
  endpoint.health.probes.enabled: true
